// file format: JavaScript

// This script is for generating random Dimeshan character names for use in Telnian Legends, and it is called via HTML.

// Given names 
// Dimeshan names are unisex, and they are for both male and female characters.
// They are generated by combining a pre-sylable and a post-sylable, with an optional secondary pre-sylable in between. The pre-sylables are two letter combinations that make up the first one or two sections of a given name, while the post-sylables are three to four letter combinations that make up the last section of a given name.

// Pre-sylables - these two letter combinations make up the first one or two sections of a given name, for example, Ti, Tita, Tala, La, and so on.

var PreSylable = [
	'Aa', 'Ae', 'Ai', 'Ao', 'Au',
	'Ba', 'Be', 'Bi', 'Bo', 'Bu',
	'Ca', 'Ce', 'Ci', 'Co', 'Cu',
	'Da', 'De', 'Di', 'Do',	'Du',
	'Ea', 'Ee', 'Ei', 'Eo', 'Eu',
	'Fa', 'Fe', 'Fi', 'Fo', 'Fu',
	'Ga', 'Ge', 'Gi', 'Go', 'Gu',
	'Ha', 'He', 'Hi', 'Ho', 'Hu',
	'Ia', 'Ie', 'Ii', 'Io', 'Iu',
	'Ja', 'Je', 'Ji', 'Jo', 'Ju',
	'Ka', 'Ke', 'Ki', 'Ko', 'Ku',
	'La', 'Le', 'Li', 'Lo', 'Lu',
	'Ma', 'Me', 'Mi', 'Mo', 'Mu',
	'Na', 'Ne', 'Ni', 'No', 'Nu',
	'Oa', 'Oe', 'Oi', 'Oo', 'Ou',
	'Pa', 'Pe', 'Pi', 'Po', 'Pu',
	'Qa', 'Qe', 'Qi', 'Qo', 'Qu',
	'Ra', 'Re', 'Ri', 'Ro', 'Ru',
	'Sa', 'Se', 'Si', 'So', 'Su',
	'Ta', 'Te', 'Ti', 'To', 'Tu',
	'Ua', 'Ue', 'Ui', 'Uo', 'Uu',
	'Va', 'Ve', 'Vi', 'Vo', 'Vu',
	'Wa', 'We', 'Wi', 'Wo', 'Wu',
	'Xa', 'Xe', 'Xi', 'Xo', 'Xu',
	'Ya', 'Ye', 'Yi', 'Yo', 'Yu',
	'Za', 'Ze', 'Zi', 'Zo', 'Zu'
]

// Post-sylables - these three to four letter combinations make up the last section of a given name, for example, -nor, -lar, -lia, -more, and so on.

var PostSylable = [
	'bab', 'baab', 'baf', 'baig', 'baag', 'bag', 'bah', 'bor', 'bore', 'biar', 'bar', 'bia', 'bif', 'been', 'beem', 'beel', 'buar',
	'cab', 'caab', 'caf', 'caig', 'caag', 'cag', 'cah', 'cor', 'core', 'ciar', 'car', 'cia', 'cif', 'ceen', 'ceem', 'ceel', 'cuar',
	'dab', 'daab', 'daf', 'daig', 'daag', 'dag', 'dah', 'dor', 'dore', 'diar', 'dar', 'dia', 'dif', 'deen', 'deem', 'deel', 'duar',
	'fab', 'faab', 'faf', 'faig', 'faag', 'fag', 'fah', 'for', 'fore', 'fiar', 'far', 'fia', 'fif', 'feen', 'feem', 'feel', 'fuar',
	'gab', 'gaab', 'gaf', 'gaig', 'gaag', 'gag', 'gah', 'gor', 'gore', 'giar', 'gar', 'gia', 'gif', 'geen', 'geem', 'geel', 'guar',
	'hab', 'haab', 'haf', 'haig', 'haag', 'hag', 'hah', 'hor', 'hore', 'hiar', 'har', 'hia', 'hif', 'heen', 'heem', 'heel', 'huar',
	'jab', 'jaab', 'jaf', 'jaig', 'jaag', 'jag', 'jah', 'jor', 'jore', 'jiar', 'jar', 'jia', 'jif', 'jeen', 'jeem', 'jeel', 'juar',
	'kab', 'kaab', 'kaf', 'kaig', 'kaag', 'kag', 'kah', 'kor', 'kore', 'kiar', 'kar', 'kia', 'kif', 'keen', 'keem', 'keel', 'kuar',
	'lab', 'laab', 'laf', 'laig', 'laag', 'lag', 'lah', 'lor', 'lore', 'liar', 'lar', 'lia', 'lif', 'leen', 'leem', 'leel', 'luar',
	'mab', 'maab', 'maf', 'maig', 'maag', 'mag', 'mah', 'mor', 'more', 'miar', 'mar', 'mia', 'mif', 'meen', 'meem', 'meel', 'muar',
	'nab', 'naab', 'naf', 'naig', 'naag', 'nag', 'nah', 'nor', 'nore', 'niar', 'nar', 'nia', 'nif', 'neen', 'neem', 'neel', 'nuar',
	'pab', 'paab', 'paf', 'paig', 'paag', 'pag', 'pah', 'por', 'pore', 'piar', 'par', 'pia', 'pif', 'peen', 'peem', 'peel', 'puar',
	'qab', 'qaab', 'qaf', 'qaig', 'qaag', 'qag', 'qah', 'qor', 'qore', 'qiar', 'qar', 'qia', 'qif', 'qeen', 'qeem', 'qeel', 'quar',
	'rab', 'raab', 'raf', 'raig', 'raag', 'rag', 'rah', 'ror', 'nore', 'riar', 'rar', 'ria', 'rif', 'reen', 'reem', 'reel', 'ruar',
	'sab', 'saab', 'saf', 'saig', 'saag', 'sag', 'sah', 'sor', 'sore', 'siar', 'sar', 'sia', 'sif', 'seen', 'seem', 'seel', 'suar',
	'tab', 'taab', 'taf', 'taig', 'taag', 'tag', 'tah', 'tor', 'tore', 'tiar', 'tar', 'tia', 'tif', 'teen', 'teem', 'teel', 'tuar',
	'vab', 'vaab', 'vaf', 'vaig', 'vaag', 'vag', 'vah', 'vor', 'vore', 'viar', 'var', 'via', 'vif', 'veen', 'veem', 'veel', 'vuar',
	'wab', 'waab', 'waf', 'waig', 'waag', 'wag', 'wah', 'wor', 'wore', 'wiar', 'war', 'wia', 'wif', 'ween', 'weem', 'weel', 'wuar',
	'xab', 'xaab', 'xaf', 'xaig', 'xaag', 'xag', 'xah', 'xor', 'xore', 'xiar', 'xar', 'xia', 'xif', 'xeen', 'xeem', 'xeel', 'xuar',
	'yab', 'yaab', 'yaf', 'yaig', 'yaag', 'yag', 'yah', 'yor', 'yore', 'viar', 'yar', 'yia', 'yif', 'yeen', 'yeem', 'yeel', 'yuar',
	'zab', 'zaab', 'zaf', 'zaig', 'zaag', 'zag', 'zah', 'zor', 'zore', 'ziar', 'zar', 'zia', 'zif', 'zeen', 'zeem', 'zeel', 'zuar'
]

function generate_given_name() {
	var randomPreIndex = PreSylable[Math.floor(Math.random() * PreSylable.length)];
	var randomSecondaryPreIndex = '';
	var randomPostIndex = PostSylable[Math.floor(Math.random() * PostSylable.length)];
	if (Math.random() >= 0.5) {
		randomSecondaryPreIndex = PreSylable[Math.floor(Math.random() * PreSylable.length)];
		randomSecondaryPreIndex = randomSecondaryPreIndex.toLowerCase();
	}
	var result = randomPreIndex + randomSecondaryPreIndex + randomPostIndex;
	return result;
}

// last names

var LastNameParts = [
	'Stone', 'Gem', 'Gold', 'Silver', 'Bronze',
	'Iron', 'Steel', 'Copper', 'Crystal', 'Diamond',
	'Emerald', 'Sapphire', 'Ruby', 'Topaz', 'Amethyst',
	'Onyx', 'Obsidian', 'Quartz', 'Jade', 'Pearl',
	'Soul', 'Spirit', 'Shadow', 'Light', 'Blue',
	'Red', 'Green', 'Black', 'White', 'Gray',
	'Dark', 'Bright', 'Silent', 'Loud', 'Swift',
	'Strong', 'Weak', 'Brave', 'Bold', 'Clever',
	'Wise', 'Fierce', 'Gentle', 'Kind', 'Noble',
	'Hearth', 'Rose', 'Lily', 'Rain', 'Sunn',
	'Moon', 'Star', 'Cloud', 'Wind', 'Fire',
	'Ice', 'Earth', 'Water', 'Air', 'Blight',
	'Storm', 'Thunder', 'Lightning', 'Frost', 'Flame',
	'Dawn', 'Dusk', 'Twilight', 'Eclipse', 'Aurora',
	'Nova', 'Comet', 'Meteor', 'Galaxy', 'Cosmos',
	'Void', 'Destiny', 'Fate', 'Wood', 'Oak',
	'Pine', 'Maple', 'Birch', 'Willow', 'Ash',
	'Elm', 'Cedar', 'Holly', 'Ivy', 'Laurel'
]

function generate_last_name() {
	var randomLastNamePart1 = LastNameParts[Math.floor(Math.random() * LastNameParts.length)];
	var randomLastNamePart2 = LastNameParts[Math.floor(Math.random() * LastNameParts.length)].toLowerCase();
	var result = randomLastNamePart1 + randomLastNamePart2;
	return result;
}

// History

var namehistory = [];

function get_history() {
	var storedHistory = localStorage.getItem("namehistory");
	if (storedHistory !== null) {
		namehistory = JSON.parse(storedHistory);
		console.log(namehistory);
		document.getElementById("history").innerHTML = namehistory.join("<br>");
	}
}

document.addEventListener('DOMContentLoaded', () => {
  // Your localStorage and innerHTML code goes here
	get_history();
});

// history limit - delete oldest entries if history exceeds 100 names

function limit_history() {
	if (namehistory.length > 100) {
		for (var i = namehistory.length - 1; i >= 100; i--) {
			namehistory.splice(i, 1);
			localStorage.setItem("namehistory", JSON.stringify(namehistory));
			document.getElementById("history").innerHTML = namehistory.join("<br>");
		}
	}
}

// Button call

function button_call_generate_names() {
	var names = [];
	for (var i = 0; i < 10; i++) {
		var name = generate_given_name() + " " + generate_last_name();
		names.unshift(name);
		namehistory.unshift(name);
	}
	console.log(names);
	localStorage.setItem("namehistory", JSON.stringify(namehistory));
	document.getElementById("generated-names").innerHTML = names.join("<br>");
	document.getElementById("history").innerHTML = namehistory.join("<br>");
	limit_history();
}

function clear_history() {
	namehistory = [];
	localStorage.removeItem("namehistory");
	document.getElementById("history").innerHTML = "";
}

